### ISSUE TITLE
Test Suite?

### ISSUE THREAD

**Issue by anthonyhastings** [antwan1986/avengers-web-application#2]
Collection is populated correctly?
Does pulling particular model from Collection give expected results?
Are models being parsed correctly?
Are model defaults working correctly?
Do the URLs in the models actually lead to 200's?
Are views templating passed in model as expected?
Are views firing appropriate global events when functions are called?

**Comment by antwan1986** [comment]
Collection is populated correctly?
Does pulling particular model from Collection give expected results?
Are models being parsed correctly?
Are model defaults working correctly?
Are views templating passed in model as expected?
Are views firing appropriate global events when functions are called?

**Comment by anthonyhastings** [comment]
Test Suite is now in place and ready to be populated.
